FROM node:latest

ENV NODE_ENV=development
WORKDIR "/app"

COPY lerna.json .
COPY package.json .
COPY package-lock.json .

COPY packages/api/package.json ./packages/api/
COPY packages/api/package-lock.json ./packages/api/

COPY packages/shared/package.json ./packages/shared/
COPY packages/shared/package-lock.json ./packages/shared/

RUN npm i

COPY packages/shared ./packages/shared/
COPY packages/api ./packages/api/

RUN npm run compile

EXPOSE 3000

CMD npm run start:api
