var g_functionCallMap = {
	StartSelectingElement: OnStartSelectingElement,
	StopSelectingElement: OnStopSelectingElement,
	TypeInto: OnTypeInto,
	Click: OnClick,
	GetElement: OnGetElement,
	GetElementStyle: OnGetElementStyle,
	GetCurrentTab: OnGetCurrentTab,
	GetTabInfo: OnGetTabInfo,
	GetText: OnGetText,
	CloseAllTabs: OnCloseAllTabs,
	NavigateTo: OnNavigateTo,
	Refresh: OnRefresh,
	GoBack: OnGoBack,
	GoForward: OnGoForward,
	InjectScript: OnInjectScript,
	InjectAsyncFunction: OnInjectAsyncFunction,
	InjectFunction: OnInjectFunction,
	GetHtml: OnGetHtml,
	GetAttribute: OnGetAttribute,
	SetAttribute: OnSetAttribute,
	SetCheckbox: OnSetCheckbox,
	SelectItems: OnSelectItems,
	GetElementVisibility: OnGetElementVisibility,
	SetProxy: OnSetProxy,
	StartBlockingResources: OnStartBlockingResources,
	StopBlockingResources: OnStopBlockingResources
};
